### General
quarkus.banner.enabled=false

### Data source
quarkus.datasource.db-kind = postgresql
quarkus.datasource.jdbc.url = ${DB_URL}
quarkus.datasource.username = ${DB_USER}
quarkus.datasource.password = ${DB_PASSWORD}

%dev.quarkus.datasource.jdbc=false
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
%dev.quarkus.datasource.username=sa
%dev.quarkus.datasource.password=

#### Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration/postgresql
%dev.quarkus.flyway.locations=classpath:db/migration/h2

### HTTP
quarkus.http.cors.enabled = true
%dev.quarkus.http.cors.origins=http://localhost

### OpenAPI
quarkus.smallrye-openapi.store-schema-directory=target/openapi
quarkus.smallrye-openapi.info-title=Example REST API
quarkus.smallrye-openapi.info-description=REST API for example service
quarkus.smallrye-openapi.info-contact-url=https://www.example.org
quarkus.smallrye-openapi.info-contact-email=support@example.org
quarkus.smallrye-openapi.info-license-name=Apache 2.0
quarkus.smallrye-openapi.info-license-url=https://www.apache.org/licenses/LICENSE-2.0.html
quarkus.smallrye-openapi.servers=https://api.example.org

### Logging
quarkus.log.console.json.enabled=true
%dev.quarkus.log.console.json.enabled=false
%dev.quarkus.log.category."org.example".level=DEBUG

### Metrics
quarkus.datasource.metrics.enabled=true
quarkus.hibernate-orm.metrics.enabled=true

### OpenTelemetry
%dev.quarkus.otel.sdk.disabled=true

### JSON serialization
quarkus.jackson.serialization-inclusion=non-null
